namespace makidice {
    partial class frmMain {
        private System.ComponentModel.IContainer components = null;
        protected override void Dispose(bool disposing) {
            if (disposing && (components != null)) {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        private void InitializeComponent() {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(frmMain));
            btn1d4 = new Button();
            lblResult = new Label();
            btn1d6 = new Button();
            btn1d8 = new Button();
            btn1d10 = new Button();
            btn1d12 = new Button();
            btn1d20 = new Button();
            btn1d100 = new Button();
            btn1 = new Button();
            btn2 = new Button();
            btn3 = new Button();
            btn4 = new Button();
            btn5 = new Button();
            btn6 = new Button();
            btn7 = new Button();
            btn8 = new Button();
            btn9 = new Button();
            btn0 = new Button();
            btnD = new Button();
            btnRoll = new Button();
            btnD10 = new Button();
            btnAbout = new Button();
            btnClear = new Button();
            SuspendLayout();
            btn1d4.Location = new Point(16, 18);
            btn1d4.Margin = new Padding(4, 5, 4, 5);
            btn1d4.Name = "btn1d4";
            btn1d4.Size = new Size(100, 35);
            btn1d4.TabIndex = 0;
            btn1d4.Text = "1d4";
            btn1d4.UseVisualStyleBackColor = true;
            btn1d4.Click += btn1d4_Click;
            lblResult.AutoSize = true;
            lblResult.Font = new Font("Segoe UI", 24F, FontStyle.Regular, GraphicsUnit.Point, 0);
            lblResult.Location = new Point(129, 208);
            lblResult.Margin = new Padding(4, 0, 4, 0);
            lblResult.Name = "lblResult";
            lblResult.RightToLeft = RightToLeft.No;
            lblResult.Size = new Size(0, 46);
            lblResult.TabIndex = 1;
            lblResult.TextAlign = ContentAlignment.MiddleCenter;
            btn1d6.Location = new Point(16, 63);
            btn1d6.Margin = new Padding(4, 5, 4, 5);
            btn1d6.Name = "btn1d6";
            btn1d6.Size = new Size(100, 35);
            btn1d6.TabIndex = 2;
            btn1d6.Text = "1d6";
            btn1d6.UseVisualStyleBackColor = true;
            btn1d6.Click += btn1d6_Click;
            btn1d8.Location = new Point(16, 108);
            btn1d8.Margin = new Padding(4, 5, 4, 5);
            btn1d8.Name = "btn1d8";
            btn1d8.Size = new Size(100, 35);
            btn1d8.TabIndex = 3;
            btn1d8.Text = "1d8";
            btn1d8.UseVisualStyleBackColor = true;
            btn1d8.Click += btn1d8_Click;
            btn1d10.Location = new Point(16, 152);
            btn1d10.Margin = new Padding(4, 5, 4, 5);
            btn1d10.Name = "btn1d10";
            btn1d10.Size = new Size(100, 35);
            btn1d10.TabIndex = 4;
            btn1d10.Text = "1d10";
            btn1d10.UseVisualStyleBackColor = true;
            btn1d10.Click += btn1d10_Click;
            btn1d12.Location = new Point(16, 197);
            btn1d12.Margin = new Padding(4, 5, 4, 5);
            btn1d12.Name = "btn1d12";
            btn1d12.Size = new Size(100, 35);
            btn1d12.TabIndex = 5;
            btn1d12.Text = "1d12";
            btn1d12.UseVisualStyleBackColor = true;
            btn1d12.Click += btn1d12_Click;
            btn1d20.Location = new Point(16, 242);
            btn1d20.Margin = new Padding(4, 5, 4, 5);
            btn1d20.Name = "btn1d20";
            btn1d20.Size = new Size(100, 35);
            btn1d20.TabIndex = 6;
            btn1d20.Text = "1d20";
            btn1d20.UseVisualStyleBackColor = true;
            btn1d20.Click += btn1d20_Click;
            btn1d100.Location = new Point(16, 286);
            btn1d100.Margin = new Padding(4, 5, 4, 5);
            btn1d100.Name = "btn1d100";
            btn1d100.Size = new Size(100, 35);
            btn1d100.TabIndex = 7;
            btn1d100.Text = "1d100";
            btn1d100.UseVisualStyleBackColor = true;
            btn1d100.Click += btn1d100_Click;
            btn1.Location = new Point(139, 18);
            btn1.Margin = new Padding(4, 5, 4, 5);
            btn1.Name = "btn1";
            btn1.Size = new Size(67, 35);
            btn1.TabIndex = 8;
            btn1.Text = "1";
            btn1.UseVisualStyleBackColor = true;
            btn1.Click += btn1_Click;
            btn2.Location = new Point(213, 18);
            btn2.Margin = new Padding(4, 5, 4, 5);
            btn2.Name = "btn2";
            btn2.Size = new Size(67, 35);
            btn2.TabIndex = 9;
            btn2.Text = "2";
            btn2.UseVisualStyleBackColor = true;
            btn2.Click += btn2_Click;
            btn3.Location = new Point(288, 18);
            btn3.Margin = new Padding(4, 5, 4, 5);
            btn3.Name = "btn3";
            btn3.Size = new Size(67, 35);
            btn3.TabIndex = 10;
            btn3.Text = "3";
            btn3.UseVisualStyleBackColor = true;
            btn3.Click += btn3_Click;
            btn4.AccessibleRole = AccessibleRole.None;
            btn4.Location = new Point(139, 63);
            btn4.Margin = new Padding(4, 5, 4, 5);
            btn4.Name = "btn4";
            btn4.Size = new Size(67, 35);
            btn4.TabIndex = 11;
            btn4.Text = "4";
            btn4.UseVisualStyleBackColor = true;
            btn4.Click += btn4_Click;
            btn5.Location = new Point(213, 63);
            btn5.Margin = new Padding(4, 5, 4, 5);
            btn5.Name = "btn5";
            btn5.Size = new Size(67, 35);
            btn5.TabIndex = 12;
            btn5.Text = "5";
            btn5.UseVisualStyleBackColor = true;
            btn5.Click += btn5_Click;
            btn6.Location = new Point(288, 63);
            btn6.Margin = new Padding(4, 5, 4, 5);
            btn6.Name = "btn6";
            btn6.Size = new Size(67, 35);
            btn6.TabIndex = 13;
            btn6.Text = "6";
            btn6.UseVisualStyleBackColor = true;
            btn6.Click += btn6_Click;
            btn7.Location = new Point(139, 108);
            btn7.Margin = new Padding(4, 5, 4, 5);
            btn7.Name = "btn7";
            btn7.Size = new Size(67, 35);
            btn7.TabIndex = 14;
            btn7.Text = "7";
            btn7.UseVisualStyleBackColor = true;
            btn7.Click += btn7_Click;
            btn8.Location = new Point(213, 108);
            btn8.Margin = new Padding(4, 5, 4, 5);
            btn8.Name = "btn8";
            btn8.Size = new Size(67, 35);
            btn8.TabIndex = 15;
            btn8.Text = "8";
            btn8.UseVisualStyleBackColor = true;
            btn8.Click += btn8_Click;
            btn9.Location = new Point(288, 108);
            btn9.Margin = new Padding(4, 5, 4, 5);
            btn9.Name = "btn9";
            btn9.Size = new Size(67, 35);
            btn9.TabIndex = 16;
            btn9.Text = "9";
            btn9.UseVisualStyleBackColor = true;
            btn9.Click += btn9_Click;
            btnD.Location = new Point(139, 152);
            btnD.Margin = new Padding(4, 5, 4, 5);
            btnD.Name = "btnD";
            btnD.Size = new Size(67, 35);
            btnD.TabIndex = 18;
            btnD.Text = "d";
            btnD.UseVisualStyleBackColor = true;
            btnD.Click += btnD_Click;
            btn0.Location = new Point(213, 152);
            btn0.Margin = new Padding(4, 5, 4, 5);
            btn0.Name = "btn0";
            btn0.Size = new Size(67, 35);
            btn0.TabIndex = 17;
            btn0.Text = "0";
            btn0.UseVisualStyleBackColor = true;
            btn0.Click += btn0_Click;
            btnRoll.Location = new Point(288, 152);
            btnRoll.Margin = new Padding(4, 5, 4, 5);
            btnRoll.Name = "btnRoll";
            btnRoll.Size = new Size(67, 35);
            btnRoll.TabIndex = 19;
            btnRoll.Text = "Roll";
            btnRoll.UseVisualStyleBackColor = true;
            btnRoll.Click += btnRoll_Click;
            btnD10.Location = new Point(213, 286);
            btnD10.Margin = new Padding(4, 5, 4, 5);
            btnD10.Name = "btnD10";
            btnD10.Size = new Size(67, 35);
            btnD10.TabIndex = 21;
            btnD10.Text = "D10";
            btnD10.UseVisualStyleBackColor = true;
            btnD10.Click += btnD10_Click;
            btnAbout.Location = new Point(288, 286);
            btnAbout.Margin = new Padding(4, 5, 4, 5);
            btnAbout.Name = "btnAbout";
            btnAbout.Size = new Size(67, 35);
            btnAbout.TabIndex = 22;
            btnAbout.Text = "About";
            btnAbout.TextImageRelation = TextImageRelation.TextAboveImage;
            btnAbout.UseVisualStyleBackColor = true;
            btnAbout.Click += btnAbout_Click;
            btnClear.Location = new Point(139, 286);
            btnClear.Margin = new Padding(4, 5, 4, 5);
            btnClear.Name = "btnClear";
            btnClear.Size = new Size(67, 35);
            btnClear.TabIndex = 20;
            btnClear.Text = "Clear";
            btnClear.UseVisualStyleBackColor = true;
            btnClear.Click += btnClear_Click;
            AutoScaleDimensions = new SizeF(8F, 20F);
            AutoScaleMode = AutoScaleMode.Font;
            ClientSize = new Size(373, 338);
            Controls.Add(btnClear);
            Controls.Add(btnAbout);
            Controls.Add(btnD10);
            Controls.Add(btnRoll);
            Controls.Add(btnD);
            Controls.Add(btn0);
            Controls.Add(btn9);
            Controls.Add(btn8);
            Controls.Add(btn7);
            Controls.Add(btn6);
            Controls.Add(btn5);
            Controls.Add(btn4);
            Controls.Add(btn3);
            Controls.Add(btn2);
            Controls.Add(btn1);
            Controls.Add(btn1d100);
            Controls.Add(btn1d20);
            Controls.Add(btn1d12);
            Controls.Add(btn1d10);
            Controls.Add(btn1d8);
            Controls.Add(btn1d6);
            Controls.Add(lblResult);
            Controls.Add(btn1d4);
            FormBorderStyle = FormBorderStyle.FixedSingle;
            Icon = (Icon)resources.GetObject("$this.Icon");
            Margin = new Padding(4, 5, 4, 5);
            MaximizeBox = false;
            Name = "frmMain";
            RightToLeft = RightToLeft.No;
            StartPosition = FormStartPosition.CenterScreen;
            Text = "Maki Dice";
            ResumeLayout(false);
            PerformLayout();
        }

        #endregion

        private System.Windows.Forms.Button btn1d4;
        private System.Windows.Forms.Label lblResult;
        private System.Windows.Forms.Button btn1d6;
        private System.Windows.Forms.Button btn1d8;
        private System.Windows.Forms.Button btn1d10;
        private System.Windows.Forms.Button btn1d12;
        private System.Windows.Forms.Button btn1d20;
        private System.Windows.Forms.Button btn1d100;
        private System.Windows.Forms.Button btn1;
        private System.Windows.Forms.Button btn2;
        private System.Windows.Forms.Button btn3;
        private System.Windows.Forms.Button btn4;
        private System.Windows.Forms.Button btn5;
        private System.Windows.Forms.Button btn6;
        private System.Windows.Forms.Button btn7;
        private System.Windows.Forms.Button btn8;
        private System.Windows.Forms.Button btn9;
        private System.Windows.Forms.Button btn0;
        private System.Windows.Forms.Button btnD;
        private System.Windows.Forms.Button btnRoll;
        private System.Windows.Forms.Button btnD10;
        private System.Windows.Forms.Button btnAbout;
        private System.Windows.Forms.Button btnClear;
    }
}